name: NuGet Generation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET @ Latest
        uses: actions/setup-dotnet@v4
        with:  
          dotnet-version: 8
          
      - name: Build solution and generate NuGet package
        run: | 
          dotnet build DynamicJSON
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push  */bin/Release/*.nupkg --skip-duplicate --no-symbols true --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
