name: NuGet Generation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    environment: DJ
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:  
          dotnet-version: 6.0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:  
          dotnet-version: 8.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
          
      - name: Build solution and generate NuGet package
        run: | 
          dotnet restore
          msbuild /t:Build /p:Configuration=Release /p:TargetFrameworks="net6.0"
          msbuild /t:Build /p:Configuration=Release /p:TargetFrameworks="net8.0"
          dotnet pack -c Release -o out

      - name: Push generated package to nuget.org registry
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: dotnet nuget push *ProrenaDynamicJSON*.nupkg --skip-duplicate --no-symbols --source "https://api.nuget.org/v3/index.json" --api-key %NUGET_AUTH_TOKEN%
    
